import { mkdirSync, rm, rmSync } from "fs";
import { join } from "path";

const badgesList: {
  name: string;
  url: string;
  href?: string;
}[] = [
  // mix of autogenerated & edited below
  {
    name: "eda33e29b6003fb10121912b0fa6d89f.gif",
    url: "https://matdoes.dev/buttons/i/eda33e29b6003fb10121912b0fa6d89f.gif",
  },
  {
    name: "3295d8e539f4804202871ce068f91b9a.gif",
    url: "https://matdoes.dev/buttons/i/3295d8e539f4804202871ce068f91b9a.gif",
  },
  {
    name: "5289c48f9da587e4b4ce771d9f7d6982.gif",
    url: "https://matdoes.dev/buttons/i/5289c48f9da587e4b4ce771d9f7d6982.gif",
  },
  {
    name: "1cb7a342492654ef51557ed1e062b27a.gif",
    href: "https://yesterweb.org/no-to-web3/",
    url: "https://matdoes.dev/buttons/i/1cb7a342492654ef51557ed1e062b27a.gif",
  },
  {
    name: "php.gif",
    href: "https://www.php.net/",
    url: "https://matdoes.dev/buttons/i/7f9386acc4b1e499677dac0cdb76c18a.gif",
  },
  {
    name: "43430008ce9affe0212f3ad93f2a8039.gif",
    url: "https://matdoes.dev/buttons/i/43430008ce9affe0212f3ad93f2a8039.gif",
  },
  {
    name: "5683c452c212818ae42f96b4ee571d5f.gif",
    href: "http://jigsaw.w3.org/css-validator/check/referer",
    url: "https://matdoes.dev/buttons/i/5683c452c212818ae42f96b4ee571d5f.gif",
  },
  {
    name: "799d287f30a0e51411aa0cf2dad3ce93.gif",
    url: "https://matdoes.dev/buttons/i/799d287f30a0e51411aa0cf2dad3ce93.gif",
  },
  {
    name: "no-js.gif",
    url: "https://matdoes.dev/buttons/i/32910724f952b771d1e8c0f0f190043c.gif",
  },
  {
    name: "d79cb5e7194dbc84adda59217234a017.gif",
    href: "https://nixos.org/",
    url: "https://matdoes.dev/buttons/i/d79cb5e7194dbc84adda59217234a017.gif",
  },
  {
    name: "ec5c39b7eb8d6eacbcd3c93201804a92.png",
    href: "https://archlinux.org/",
    url: "https://matdoes.dev/buttons/i/ec5c39b7eb8d6eacbcd3c93201804a92.png",
  },
  {
    name: "7f6c5065dc7ec10b6e1a2bb83fd4932e.png",
    url: "https://matdoes.dev/buttons/i/7f6c5065dc7ec10b6e1a2bb83fd4932e.png",
  },
  {
    name: "de419e561cbb72e6f898381e60a0ba2f.gif",
    href: "https://ohdhie7qka42mvxcl2lb5bcxw6jumwn6lbqdmpli3xxhktvyqg2gtryd.onion/retro",
    url: "https://matdoes.dev/buttons/i/de419e561cbb72e6f898381e60a0ba2f.gif",
  },
  {
    name: "2459bbdeee32fcf23708f776f4c9153b.gif",
    href: "https://www.w3.org/TR/html4/",
    url: "https://matdoes.dev/buttons/i/2459bbdeee32fcf23708f776f4c9153b.gif",
  },
  {
    name: "e56bd48e53ba130e30bdba37265dc64b.gif",
    href: "https://privacytests.org/",
    url: "https://matdoes.dev/buttons/i/e56bd48e53ba130e30bdba37265dc64b.gif",
  },
  {
    name: "512kb-orange.gif",
    href: "https://512kb.club/",
    url: "https://512kb.club/assets/images/orange-team.gif",
  },
  {
    name: "512kb.webp",
    href: "https://512kb.club/",
    url: "https://matdoes.dev/buttons/i/03bae40593e77e1b382c3ae41c4d7078.webp",
  },
  {
    name: "99a4d00a82cc786a1a666ad70bf4e8af.gif",
    url: "https://matdoes.dev/buttons/i/99a4d00a82cc786a1a666ad70bf4e8af.gif",
  },
  {
    name: "653d8c992fe0190456286de2b4877f9e.gif",
    href: "https://code.visualstudio.com/",
    url: "https://matdoes.dev/buttons/i/653d8c992fe0190456286de2b4877f9e.gif",
  },
  {
    name: "760ce10482bf8260df45c50fd2d5571a.gif",
    url: "https://matdoes.dev/buttons/i/760ce10482bf8260df45c50fd2d5571a.gif",
  },
];
const badgesDir = join(__dirname, "..", "src", "badges");
rmSync(badgesDir, { recursive: true });
mkdirSync(badgesDir);
badgesList.forEach((badge) => {
  console.log(`Downloading ${badge.name}`);
  console.timeLog(badge.name);
  fetch(badge.url)
    .then((r) => r.arrayBuffer())
    .then((arBuff) => {
      console.timeEnd(badge.name);
      console.log(`Downloaded ${badge.name}`);
      Bun.write(join(badgesDir, badge.name), Buffer.from(arBuff));
    });
});

Bun.write(join(badgesDir, "..", "badges.json"), JSON.stringify(badgesList));
